### ISSUE TITLE
Console Issue

### ISSUE THREAD

**Issue by Piratian** [EmpyrealHell/wolfpack-rpg-client#7]
Hello, when using 3 commands in a row, the console freezes and stops putting out text and doesn't show more commands.  I first noticed this when I Queued for a dungeon and was leader, and started, then queued again and couldn't start the second time.  I also tested it again with checked 3 pets and then couldn't do anything anymore after that.  The issue started recently as I believe a week ago I queued for like 10 dungeons in a row and didn't have any issue.

**Comment by EmpyrealHell** [comment]
There is a limiter in place, based on the limits twitch sets for 3rd-party clients, listed [here](https://dev.twitch.tv/docs/irc/guide) under command and message limits for whispers. It should let commands go through after a very short delay if you send more than three in a row, but it sounds like the limiter may be configured incorrectly, or just not working right. I'll take a look at it later today

**Comment by EmpyrealHell** [comment]
I'm pretty sure I know what the problem is now. If the timer rolled over all 3 occurrences in the same tick, it would never remove any of them, because it was only removing occurrences if it found any in the list that were still within the timer range. If they all fall out at the same time, it will never hit that, and all 3 will remain locked in the list. I think I have a fix in place, but it needs more testing. I'll address the tests this evening.
