### ISSUE TITLE
Stuck Fetching tournament data...

### ISSUE THREAD

**Issue by Lilmacaco** [EmpyrealHell/wolfpack-rpg-client#73]
Anytime I load the wolfpack-rpg-client in Firefox it just stays stuck at Fetching tournament data... and I can send more commands down but nothing happens.

Firefox version 110.0 (64-bit)

Attached screenshot of broken wolfpack RPG
![WolfpackBroken](https://user-images.githubusercontent.com/6832714/221660512-26a88ed3-68a3-4e51-94ba-775cccbef2ce.png)

**Comment by EmpyrealHell** [comment]
Usually when this happens it's because lobot has crashed and lobos needs to restart it (he runs it directly from his stream pc, so he's the only one who can).
You can verify if this is the case by checking your whispers directly on twitch. If you don't see any responses there then the bot is just down. If you are seeing whispers there though, let me know and I'll see if I can help you get some extra detail I would need to figure out what's going on.
