### ISSUE TITLE
New Line Placed Before Previous Command

### ISSUE THREAD

**Issue by Trinnith** [EmpyrealHell/wolfpack-rpg-client#8]
Repro Steps:
1. Access the client (v 1.0.2) fresh or re-load the page
2. Issue any valid command (in this case, "!queuetime") and wait for lobot's reply
3. Issue another valid command (I used "!pets")
4. Notice that an empty line is added to the console above the previous command

This trend continues until the 4th attempted command where the console ceases to respond. 
P.S.
I absolutely love this tool, I didn't play the RPG until now because I hated whispers. Thanks!

**Comment by EmpyrealHell** [comment]
The new line is intentional, as a way to group the message its response separate from other messages. The empty line should be there as soon as you send the message though, not pop in after the next message. I will look into that this evening.

As for the other part about the 4th message not sending, this is being addressed in #7.

**Comment by Trinnith** [comment]
After a little bit of digging, I have found the culprit newline to be the one added in the onWhisper of irc.service.ts (line 100). My angular skills are a bit rusty but if I figure out why it's always acting on the previous message only, I'll PR!

**Comment by EmpyrealHell** [comment]
Those are both easy fixes, thank you for getting the details for me. I'm out right now, so if you can get to it within the next 5 hours, it's all yours, otherwise I'll take care of it then. If you're going to make a PR, make sure you read the contribution guidelines, because we're probably going to want a test for this one. It should have had one anyway, I just missed it.
